version: "3"

services:
  bghq_redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis_data:
